"""Add EpoxyStyle

Revision ID: 2bf66799e35a
Revises: 001_initial_schema
Create Date: 2026-01-20 20:55:55.029309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf66799e35a'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epoxy_styles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('cover_image_id', sa.Uuid(), nullable=True),
    sa.Column('texture_maps', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['cover_image_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epoxy_styles_category'), 'epoxy_styles', ['category'], unique=False)
    op.create_index(op.f('ix_epoxy_styles_name'), 'epoxy_styles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epoxy_styles_name'), table_name='epoxy_styles')
    op.drop_index(op.f('ix_epoxy_styles_category'), table_name='epoxy_styles')
    op.drop_table('epoxy_styles')
    # ### end Alembic commands ###
