"""add_project_id_to_styles

Revision ID: c3b27c1d1650
Revises: ee76edde8104
Create Date: 2026-01-22 19:24:56.811731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b27c1d1650'
down_revision: Union[str, None] = 'ee76edde8104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epoxy_styles', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'epoxy_styles', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'epoxy_styles', type_='foreignkey')
    op.drop_column('epoxy_styles', 'project_id')
    # ### end Alembic commands ###
